#!/bin/bash
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_LPIPS/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_LPIPS/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_LPIPS/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_LPIPS/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_LPIPS/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_SSIM/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_SSIM/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_SSIM/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_SSIM/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_SSIM/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L2/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L2/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L2/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L2/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L2/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L1/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L1/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L1/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L1/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_L1/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_none/20 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_none/40 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_none/60 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_none/half --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --pixel_based --outdir ./images/ablation/celeba-hq/pixel_none/ex64 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type ex64 --device 0





python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_LPIPS/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_LPIPS/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_LPIPS/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_LPIPS/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_LPIPS/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_SSIM/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_SSIM/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_SSIM/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_SSIM/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_SSIM/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L2/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L2/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L2/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L2/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L2/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L1/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L1/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L1/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L1/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_L1/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_none/20 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_none/40 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_none/60 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_none/half --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --mask_aware --outdir ./images/ablation/celeba-hq/mask_none/ex64 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type ex64 --device 0




python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_LPIPS/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_LPIPS/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_LPIPS/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_LPIPS/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_LPIPS/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss LPIPS --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_SSIM/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_SSIM/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_SSIM/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_SSIM/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_SSIM/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss SSIM --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L2/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L2/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L2/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L2/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L2/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L2 --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L1/20 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L1/40 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L1/60 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L1/half --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_L1/ex64 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 1 --optimize_xt.loss L1 --mask_type ex64 --device 0

python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_none/20 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 20 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_none/40 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 40 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_none/60 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type 60 --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_none/half --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type half --device 0
python main.py --config_file configs/celebahq.yaml --outdir ./images/ablation/celeba-hq/none_none/ex64 --ddim.schedule_params.ddpm_num_steps 1000 --ddim.schedule_params.num_inference_steps 1000 --timestep_respacing 1000 --optimize_xt.lr_xt_decay 1 --optimize_xt.num_iteration_optimize_xt 0 --mask_type ex64 --device 0